load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "query",
    srcs = [
        "do_query.go",
        "encode.go",
        "expression.go",
        "parser.go",
    ],
    importpath = "bonanza.build/pkg/bazelclient/commands/query",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/bazelclient/arguments",
        "//pkg/bazelclient/commands",
        "//pkg/bazelclient/commands/build",
        "//pkg/bazelclient/formatted",
        "//pkg/bazelclient/logging",
        "//pkg/crypto",
        "//pkg/label",
        "//pkg/model/core",
        "//pkg/model/core/btree",
        "//pkg/model/encoding",
        "//pkg/model/evaluation",
        "//pkg/model/executewithstorage",
        "//pkg/model/filesystem",
        "//pkg/model/parser",
        "//pkg/proto/encryptedaction",
        "//pkg/proto/model/analysis",
        "//pkg/proto/model/core",
        "//pkg/proto/model/encoding",
        "//pkg/proto/model/evaluation",
        "//pkg/proto/model/executewithstorage",
        "//pkg/proto/model/filesystem",
        "//pkg/proto/remoteexecution",
        "//pkg/proto/storage/dag",
        "//pkg/proto/storage/object",
        "//pkg/remoteexecution",
        "//pkg/starlark",
        "//pkg/storage/dag",
        "//pkg/storage/dag/grpc",
        "//pkg/storage/object",
        "//pkg/storage/object/grpc",
        "//pkg/storage/object/namespacemapping",
        "@com_github_buildbarn_bb_storage//pkg/eviction",
        "@com_github_buildbarn_bb_storage//pkg/filesystem",
        "@com_github_buildbarn_bb_storage//pkg/filesystem/path",
        "@com_github_buildbarn_bb_storage//pkg/util",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//status",
        "@org_golang_google_grpc_security_advancedtls//:advancedtls",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/emptypb",
        "@org_golang_x_sync//errgroup",
        "@org_golang_x_sync//semaphore",
    ],
)

go_test(
    name = "query_test",
    size = "small",
    srcs = ["parser_test.go"],
    deps = [
        ":query",
        "@com_github_stretchr_testify//require",
    ],
)

go_test(
    name = "query_source_test",
    srcs = ["source_exclusions_test.go"],
    embed = [":query"],
    deps = [
        "//pkg/bazelclient/commands/build",
        "//pkg/bazelclient/formatted",
        "//pkg/bazelclient/logging",
        "//pkg/model/core",
        "@com_github_buildbarn_bb_storage//pkg/filesystem",
        "@com_github_buildbarn_bb_storage//pkg/filesystem/path",
        "@com_github_stretchr_testify//require",
    ],
)
