// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: bonanza.build/pkg/proto/storage/dag/dag.proto

package dag

import (
	object "bonanza.build/pkg/proto/storage/object"
	tag "bonanza.build/pkg/proto/storage/tag"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadDagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*UploadDagsRequest_Handshake_
	//	*UploadDagsRequest_InitiateDag_
	//	*UploadDagsRequest_ProvideObjectContents_
	Type          isUploadDagsRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDagsRequest) Reset() {
	*x = UploadDagsRequest{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest) ProtoMessage() {}

func (x *UploadDagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0}
}

func (x *UploadDagsRequest) GetType() isUploadDagsRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *UploadDagsRequest) GetHandshake() *UploadDagsRequest_Handshake {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsRequest_Handshake_); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *UploadDagsRequest) GetInitiateDag() *UploadDagsRequest_InitiateDag {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsRequest_InitiateDag_); ok {
			return x.InitiateDag
		}
	}
	return nil
}

func (x *UploadDagsRequest) GetProvideObjectContents() *UploadDagsRequest_ProvideObjectContents {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsRequest_ProvideObjectContents_); ok {
			return x.ProvideObjectContents
		}
	}
	return nil
}

type isUploadDagsRequest_Type interface {
	isUploadDagsRequest_Type()
}

type UploadDagsRequest_Handshake_ struct {
	Handshake *UploadDagsRequest_Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type UploadDagsRequest_InitiateDag_ struct {
	InitiateDag *UploadDagsRequest_InitiateDag `protobuf:"bytes,2,opt,name=initiate_dag,json=initiateDag,proto3,oneof"`
}

type UploadDagsRequest_ProvideObjectContents_ struct {
	ProvideObjectContents *UploadDagsRequest_ProvideObjectContents `protobuf:"bytes,3,opt,name=provide_object_contents,json=provideObjectContents,proto3,oneof"`
}

func (*UploadDagsRequest_Handshake_) isUploadDagsRequest_Type() {}

func (*UploadDagsRequest_InitiateDag_) isUploadDagsRequest_Type() {}

func (*UploadDagsRequest_ProvideObjectContents_) isUploadDagsRequest_Type() {}

type UploadDagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*UploadDagsResponse_Handshake_
	//	*UploadDagsResponse_RequestObjectContents_
	//	*UploadDagsResponse_FinalizeObject_
	//	*UploadDagsResponse_FinalizeTag_
	Type          isUploadDagsResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDagsResponse) Reset() {
	*x = UploadDagsResponse{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse) ProtoMessage() {}

func (x *UploadDagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDagsResponse) GetType() isUploadDagsResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *UploadDagsResponse) GetHandshake() *UploadDagsResponse_Handshake {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsResponse_Handshake_); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *UploadDagsResponse) GetRequestObjectContents() *UploadDagsResponse_RequestObjectContents {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsResponse_RequestObjectContents_); ok {
			return x.RequestObjectContents
		}
	}
	return nil
}

func (x *UploadDagsResponse) GetFinalizeObject() *UploadDagsResponse_FinalizeObject {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsResponse_FinalizeObject_); ok {
			return x.FinalizeObject
		}
	}
	return nil
}

func (x *UploadDagsResponse) GetFinalizeTag() *UploadDagsResponse_FinalizeTag {
	if x != nil {
		if x, ok := x.Type.(*UploadDagsResponse_FinalizeTag_); ok {
			return x.FinalizeTag
		}
	}
	return nil
}

type isUploadDagsResponse_Type interface {
	isUploadDagsResponse_Type()
}

type UploadDagsResponse_Handshake_ struct {
	Handshake *UploadDagsResponse_Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type UploadDagsResponse_RequestObjectContents_ struct {
	RequestObjectContents *UploadDagsResponse_RequestObjectContents `protobuf:"bytes,2,opt,name=request_object_contents,json=requestObjectContents,proto3,oneof"`
}

type UploadDagsResponse_FinalizeObject_ struct {
	FinalizeObject *UploadDagsResponse_FinalizeObject `protobuf:"bytes,3,opt,name=finalize_object,json=finalizeObject,proto3,oneof"`
}

type UploadDagsResponse_FinalizeTag_ struct {
	FinalizeTag *UploadDagsResponse_FinalizeTag `protobuf:"bytes,4,opt,name=finalize_tag,json=finalizeTag,proto3,oneof"`
}

func (*UploadDagsResponse_Handshake_) isUploadDagsResponse_Type() {}

func (*UploadDagsResponse_RequestObjectContents_) isUploadDagsResponse_Type() {}

func (*UploadDagsResponse_FinalizeObject_) isUploadDagsResponse_Type() {}

func (*UploadDagsResponse_FinalizeTag_) isUploadDagsResponse_Type() {}

type UploadDagsRequest_Handshake struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Namespace                      *object.Namespace      `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MaximumUnfinalizedParentsLimit *object.Limit          `protobuf:"bytes,2,opt,name=maximum_unfinalized_parents_limit,json=maximumUnfinalizedParentsLimit,proto3" json:"maximum_unfinalized_parents_limit,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *UploadDagsRequest_Handshake) Reset() {
	*x = UploadDagsRequest_Handshake{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest_Handshake) ProtoMessage() {}

func (x *UploadDagsRequest_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest_Handshake.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest_Handshake) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UploadDagsRequest_Handshake) GetNamespace() *object.Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *UploadDagsRequest_Handshake) GetMaximumUnfinalizedParentsLimit() *object.Limit {
	if x != nil {
		return x.MaximumUnfinalizedParentsLimit
	}
	return nil
}

type UploadDagsRequest_InitiateDag struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	RootReference []byte                             `protobuf:"bytes,1,opt,name=root_reference,json=rootReference,proto3" json:"root_reference,omitempty"`
	RootTag       *UploadDagsRequest_InitiateDag_Tag `protobuf:"bytes,2,opt,name=root_tag,json=rootTag,proto3" json:"root_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDagsRequest_InitiateDag) Reset() {
	*x = UploadDagsRequest_InitiateDag{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest_InitiateDag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest_InitiateDag) ProtoMessage() {}

func (x *UploadDagsRequest_InitiateDag) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest_InitiateDag.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest_InitiateDag) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UploadDagsRequest_InitiateDag) GetRootReference() []byte {
	if x != nil {
		return x.RootReference
	}
	return nil
}

func (x *UploadDagsRequest_InitiateDag) GetRootTag() *UploadDagsRequest_InitiateDag_Tag {
	if x != nil {
		return x.RootTag
	}
	return nil
}

type UploadDagsRequest_ProvideObjectContents struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LowestReferenceIndex uint64                 `protobuf:"varint,1,opt,name=lowest_reference_index,json=lowestReferenceIndex,proto3" json:"lowest_reference_index,omitempty"`
	ObjectContents       []byte                 `protobuf:"bytes,2,opt,name=object_contents,json=objectContents,proto3" json:"object_contents,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UploadDagsRequest_ProvideObjectContents) Reset() {
	*x = UploadDagsRequest_ProvideObjectContents{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest_ProvideObjectContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest_ProvideObjectContents) ProtoMessage() {}

func (x *UploadDagsRequest_ProvideObjectContents) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest_ProvideObjectContents.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest_ProvideObjectContents) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0, 2}
}

func (x *UploadDagsRequest_ProvideObjectContents) GetLowestReferenceIndex() uint64 {
	if x != nil {
		return x.LowestReferenceIndex
	}
	return 0
}

func (x *UploadDagsRequest_ProvideObjectContents) GetObjectContents() []byte {
	if x != nil {
		return x.ObjectContents
	}
	return nil
}

type UploadDagsRequest_InitiateDag_Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *tag.Key               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDagsRequest_InitiateDag_Tag) Reset() {
	*x = UploadDagsRequest_InitiateDag_Tag{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsRequest_InitiateDag_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsRequest_InitiateDag_Tag) ProtoMessage() {}

func (x *UploadDagsRequest_InitiateDag_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsRequest_InitiateDag_Tag.ProtoReflect.Descriptor instead.
func (*UploadDagsRequest_InitiateDag_Tag) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *UploadDagsRequest_InitiateDag_Tag) GetKey() *tag.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *UploadDagsRequest_InitiateDag_Tag) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UploadDagsRequest_InitiateDag_Tag) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type UploadDagsResponse_Handshake struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	MaximumUnfinalizedDagsCount uint32                 `protobuf:"varint,1,opt,name=maximum_unfinalized_dags_count,json=maximumUnfinalizedDagsCount,proto3" json:"maximum_unfinalized_dags_count,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UploadDagsResponse_Handshake) Reset() {
	*x = UploadDagsResponse_Handshake{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse_Handshake) ProtoMessage() {}

func (x *UploadDagsResponse_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse_Handshake.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse_Handshake) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UploadDagsResponse_Handshake) GetMaximumUnfinalizedDagsCount() uint32 {
	if x != nil {
		return x.MaximumUnfinalizedDagsCount
	}
	return 0
}

type UploadDagsResponse_RequestObjectContents struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LowestReferenceIndex uint64                 `protobuf:"varint,1,opt,name=lowest_reference_index,json=lowestReferenceIndex,proto3" json:"lowest_reference_index,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UploadDagsResponse_RequestObjectContents) Reset() {
	*x = UploadDagsResponse_RequestObjectContents{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse_RequestObjectContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse_RequestObjectContents) ProtoMessage() {}

func (x *UploadDagsResponse_RequestObjectContents) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse_RequestObjectContents.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse_RequestObjectContents) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1, 1}
}

func (x *UploadDagsResponse_RequestObjectContents) GetLowestReferenceIndex() uint64 {
	if x != nil {
		return x.LowestReferenceIndex
	}
	return 0
}

type UploadDagsResponse_FinalizeObject struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	LowestReferenceIndex       uint64                 `protobuf:"varint,1,opt,name=lowest_reference_index,json=lowestReferenceIndex,proto3" json:"lowest_reference_index,omitempty"`
	AdditionalReferenceIndices uint32                 `protobuf:"varint,2,opt,name=additional_reference_indices,json=additionalReferenceIndices,proto3" json:"additional_reference_indices,omitempty"`
	Status                     *status.Status         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UploadDagsResponse_FinalizeObject) Reset() {
	*x = UploadDagsResponse_FinalizeObject{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse_FinalizeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse_FinalizeObject) ProtoMessage() {}

func (x *UploadDagsResponse_FinalizeObject) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse_FinalizeObject.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse_FinalizeObject) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1, 2}
}

func (x *UploadDagsResponse_FinalizeObject) GetLowestReferenceIndex() uint64 {
	if x != nil {
		return x.LowestReferenceIndex
	}
	return 0
}

func (x *UploadDagsResponse_FinalizeObject) GetAdditionalReferenceIndices() uint32 {
	if x != nil {
		return x.AdditionalReferenceIndices
	}
	return 0
}

func (x *UploadDagsResponse_FinalizeObject) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type UploadDagsResponse_FinalizeTag struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RootReferenceIndex uint64                 `protobuf:"varint,1,opt,name=root_reference_index,json=rootReferenceIndex,proto3" json:"root_reference_index,omitempty"`
	Status             *status.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UploadDagsResponse_FinalizeTag) Reset() {
	*x = UploadDagsResponse_FinalizeTag{}
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDagsResponse_FinalizeTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDagsResponse_FinalizeTag) ProtoMessage() {}

func (x *UploadDagsResponse_FinalizeTag) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDagsResponse_FinalizeTag.ProtoReflect.Descriptor instead.
func (*UploadDagsResponse_FinalizeTag) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP(), []int{1, 3}
}

func (x *UploadDagsResponse_FinalizeTag) GetRootReferenceIndex() uint64 {
	if x != nil {
		return x.RootReferenceIndex
	}
	return 0
}

func (x *UploadDagsResponse_FinalizeTag) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_bonanza_build_pkg_proto_storage_dag_dag_proto protoreflect.FileDescriptor

const file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDesc = "" +
	"\n" +
	"-bonanza.build/pkg/proto/storage/dag/dag.proto\x12\x13bonanza.storage.dag\x1a3bonanza.build/pkg/proto/storage/object/object.proto\x1a-bonanza.build/pkg/proto/storage/tag/tag.proto\x1a\x17google/rpc/status.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\a\n" +
	"\x11UploadDagsRequest\x12P\n" +
	"\thandshake\x18\x01 \x01(\v20.bonanza.storage.dag.UploadDagsRequest.HandshakeH\x00R\thandshake\x12W\n" +
	"\finitiate_dag\x18\x02 \x01(\v22.bonanza.storage.dag.UploadDagsRequest.InitiateDagH\x00R\vinitiateDag\x12v\n" +
	"\x17provide_object_contents\x18\x03 \x01(\v2<.bonanza.storage.dag.UploadDagsRequest.ProvideObjectContentsH\x00R\x15provideObjectContents\x1a\xb6\x01\n" +
	"\tHandshake\x12?\n" +
	"\tnamespace\x18\x01 \x01(\v2!.bonanza.storage.object.NamespaceR\tnamespace\x12h\n" +
	"!maximum_unfinalized_parents_limit\x18\x02 \x01(\v2\x1d.bonanza.storage.object.LimitR\x1emaximumUnfinalizedParentsLimit\x1a\x93\x02\n" +
	"\vInitiateDag\x12%\n" +
	"\x0eroot_reference\x18\x01 \x01(\fR\rrootReference\x12Q\n" +
	"\broot_tag\x18\x02 \x01(\v26.bonanza.storage.dag.UploadDagsRequest.InitiateDag.TagR\arootTag\x1a\x89\x01\n" +
	"\x03Tag\x12*\n" +
	"\x03key\x18\x01 \x01(\v2\x18.bonanza.storage.tag.KeyR\x03key\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x1av\n" +
	"\x15ProvideObjectContents\x124\n" +
	"\x16lowest_reference_index\x18\x01 \x01(\x04R\x14lowestReferenceIndex\x12'\n" +
	"\x0fobject_contents\x18\x02 \x01(\fR\x0eobjectContentsB\x06\n" +
	"\x04type\"\xea\x06\n" +
	"\x12UploadDagsResponse\x12Q\n" +
	"\thandshake\x18\x01 \x01(\v21.bonanza.storage.dag.UploadDagsResponse.HandshakeH\x00R\thandshake\x12w\n" +
	"\x17request_object_contents\x18\x02 \x01(\v2=.bonanza.storage.dag.UploadDagsResponse.RequestObjectContentsH\x00R\x15requestObjectContents\x12a\n" +
	"\x0ffinalize_object\x18\x03 \x01(\v26.bonanza.storage.dag.UploadDagsResponse.FinalizeObjectH\x00R\x0efinalizeObject\x12X\n" +
	"\ffinalize_tag\x18\x04 \x01(\v23.bonanza.storage.dag.UploadDagsResponse.FinalizeTagH\x00R\vfinalizeTag\x1aP\n" +
	"\tHandshake\x12C\n" +
	"\x1emaximum_unfinalized_dags_count\x18\x01 \x01(\rR\x1bmaximumUnfinalizedDagsCount\x1aM\n" +
	"\x15RequestObjectContents\x124\n" +
	"\x16lowest_reference_index\x18\x01 \x01(\x04R\x14lowestReferenceIndex\x1a\xb4\x01\n" +
	"\x0eFinalizeObject\x124\n" +
	"\x16lowest_reference_index\x18\x01 \x01(\x04R\x14lowestReferenceIndex\x12@\n" +
	"\x1cadditional_reference_indices\x18\x02 \x01(\rR\x1aadditionalReferenceIndices\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x06status\x1ak\n" +
	"\vFinalizeTag\x120\n" +
	"\x14root_reference_index\x18\x01 \x01(\x04R\x12rootReferenceIndex\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06statusB\x06\n" +
	"\x04type2m\n" +
	"\bUploader\x12a\n" +
	"\n" +
	"UploadDags\x12&.bonanza.storage.dag.UploadDagsRequest\x1a'.bonanza.storage.dag.UploadDagsResponse(\x010\x01B%Z#bonanza.build/pkg/proto/storage/dagb\x06proto3"

var (
	file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescOnce sync.Once
	file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescData []byte
)

func file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescGZIP() []byte {
	file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescOnce.Do(func() {
		file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDesc), len(file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDesc)))
	})
	return file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDescData
}

var file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bonanza_build_pkg_proto_storage_dag_dag_proto_goTypes = []any{
	(*UploadDagsRequest)(nil),                        // 0: bonanza.storage.dag.UploadDagsRequest
	(*UploadDagsResponse)(nil),                       // 1: bonanza.storage.dag.UploadDagsResponse
	(*UploadDagsRequest_Handshake)(nil),              // 2: bonanza.storage.dag.UploadDagsRequest.Handshake
	(*UploadDagsRequest_InitiateDag)(nil),            // 3: bonanza.storage.dag.UploadDagsRequest.InitiateDag
	(*UploadDagsRequest_ProvideObjectContents)(nil),  // 4: bonanza.storage.dag.UploadDagsRequest.ProvideObjectContents
	(*UploadDagsRequest_InitiateDag_Tag)(nil),        // 5: bonanza.storage.dag.UploadDagsRequest.InitiateDag.Tag
	(*UploadDagsResponse_Handshake)(nil),             // 6: bonanza.storage.dag.UploadDagsResponse.Handshake
	(*UploadDagsResponse_RequestObjectContents)(nil), // 7: bonanza.storage.dag.UploadDagsResponse.RequestObjectContents
	(*UploadDagsResponse_FinalizeObject)(nil),        // 8: bonanza.storage.dag.UploadDagsResponse.FinalizeObject
	(*UploadDagsResponse_FinalizeTag)(nil),           // 9: bonanza.storage.dag.UploadDagsResponse.FinalizeTag
	(*object.Namespace)(nil),                         // 10: bonanza.storage.object.Namespace
	(*object.Limit)(nil),                             // 11: bonanza.storage.object.Limit
	(*tag.Key)(nil),                                  // 12: bonanza.storage.tag.Key
	(*timestamppb.Timestamp)(nil),                    // 13: google.protobuf.Timestamp
	(*status.Status)(nil),                            // 14: google.rpc.Status
}
var file_bonanza_build_pkg_proto_storage_dag_dag_proto_depIdxs = []int32{
	2,  // 0: bonanza.storage.dag.UploadDagsRequest.handshake:type_name -> bonanza.storage.dag.UploadDagsRequest.Handshake
	3,  // 1: bonanza.storage.dag.UploadDagsRequest.initiate_dag:type_name -> bonanza.storage.dag.UploadDagsRequest.InitiateDag
	4,  // 2: bonanza.storage.dag.UploadDagsRequest.provide_object_contents:type_name -> bonanza.storage.dag.UploadDagsRequest.ProvideObjectContents
	6,  // 3: bonanza.storage.dag.UploadDagsResponse.handshake:type_name -> bonanza.storage.dag.UploadDagsResponse.Handshake
	7,  // 4: bonanza.storage.dag.UploadDagsResponse.request_object_contents:type_name -> bonanza.storage.dag.UploadDagsResponse.RequestObjectContents
	8,  // 5: bonanza.storage.dag.UploadDagsResponse.finalize_object:type_name -> bonanza.storage.dag.UploadDagsResponse.FinalizeObject
	9,  // 6: bonanza.storage.dag.UploadDagsResponse.finalize_tag:type_name -> bonanza.storage.dag.UploadDagsResponse.FinalizeTag
	10, // 7: bonanza.storage.dag.UploadDagsRequest.Handshake.namespace:type_name -> bonanza.storage.object.Namespace
	11, // 8: bonanza.storage.dag.UploadDagsRequest.Handshake.maximum_unfinalized_parents_limit:type_name -> bonanza.storage.object.Limit
	5,  // 9: bonanza.storage.dag.UploadDagsRequest.InitiateDag.root_tag:type_name -> bonanza.storage.dag.UploadDagsRequest.InitiateDag.Tag
	12, // 10: bonanza.storage.dag.UploadDagsRequest.InitiateDag.Tag.key:type_name -> bonanza.storage.tag.Key
	13, // 11: bonanza.storage.dag.UploadDagsRequest.InitiateDag.Tag.timestamp:type_name -> google.protobuf.Timestamp
	14, // 12: bonanza.storage.dag.UploadDagsResponse.FinalizeObject.status:type_name -> google.rpc.Status
	14, // 13: bonanza.storage.dag.UploadDagsResponse.FinalizeTag.status:type_name -> google.rpc.Status
	0,  // 14: bonanza.storage.dag.Uploader.UploadDags:input_type -> bonanza.storage.dag.UploadDagsRequest
	1,  // 15: bonanza.storage.dag.Uploader.UploadDags:output_type -> bonanza.storage.dag.UploadDagsResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_bonanza_build_pkg_proto_storage_dag_dag_proto_init() }
func file_bonanza_build_pkg_proto_storage_dag_dag_proto_init() {
	if File_bonanza_build_pkg_proto_storage_dag_dag_proto != nil {
		return
	}
	file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadDagsRequest_Handshake_)(nil),
		(*UploadDagsRequest_InitiateDag_)(nil),
		(*UploadDagsRequest_ProvideObjectContents_)(nil),
	}
	file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadDagsResponse_Handshake_)(nil),
		(*UploadDagsResponse_RequestObjectContents_)(nil),
		(*UploadDagsResponse_FinalizeObject_)(nil),
		(*UploadDagsResponse_FinalizeTag_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDesc), len(file_bonanza_build_pkg_proto_storage_dag_dag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bonanza_build_pkg_proto_storage_dag_dag_proto_goTypes,
		DependencyIndexes: file_bonanza_build_pkg_proto_storage_dag_dag_proto_depIdxs,
		MessageInfos:      file_bonanza_build_pkg_proto_storage_dag_dag_proto_msgTypes,
	}.Build()
	File_bonanza_build_pkg_proto_storage_dag_dag_proto = out.File
	file_bonanza_build_pkg_proto_storage_dag_dag_proto_goTypes = nil
	file_bonanza_build_pkg_proto_storage_dag_dag_proto_depIdxs = nil
}
