// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: bonanza.build/pkg/proto/configuration/bonanza_worker/bonanza_worker.proto

package bonanza_worker

import (
	parser "bonanza.build/pkg/proto/configuration/model/parser"
	local "bonanza.build/pkg/proto/configuration/storage/object/local"
	filesystem "github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem"
	virtual "github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem/virtual"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	x509 "github.com/buildbarn/bb-storage/pkg/proto/configuration/x509"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReapiRunnerConfiguration_Queue int32

const (
	ReapiRunnerConfiguration_QUEUE_UNSPECIFIED ReapiRunnerConfiguration_Queue = 0
	ReapiRunnerConfiguration_QUEUE_SMALL       ReapiRunnerConfiguration_Queue = 1
	ReapiRunnerConfiguration_QUEUE_LINK        ReapiRunnerConfiguration_Queue = 2
)

// Enum value maps for ReapiRunnerConfiguration_Queue.
var (
	ReapiRunnerConfiguration_Queue_name = map[int32]string{
		0: "QUEUE_UNSPECIFIED",
		1: "QUEUE_SMALL",
		2: "QUEUE_LINK",
	}
	ReapiRunnerConfiguration_Queue_value = map[string]int32{
		"QUEUE_UNSPECIFIED": 0,
		"QUEUE_SMALL":       1,
		"QUEUE_LINK":        2,
	}
)

func (x ReapiRunnerConfiguration_Queue) Enum() *ReapiRunnerConfiguration_Queue {
	p := new(ReapiRunnerConfiguration_Queue)
	*p = x
	return p
}

func (x ReapiRunnerConfiguration_Queue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReapiRunnerConfiguration_Queue) Descriptor() protoreflect.EnumDescriptor {
	return file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_enumTypes[0].Descriptor()
}

func (ReapiRunnerConfiguration_Queue) Type() protoreflect.EnumType {
	return &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_enumTypes[0]
}

func (x ReapiRunnerConfiguration_Queue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReapiRunnerConfiguration_Queue.Descriptor instead.
func (ReapiRunnerConfiguration_Queue) EnumDescriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP(), []int{3, 0}
}

type ApplicationConfiguration struct {
	state                  protoimpl.MessageState            `protogen:"open.v1"`
	Global                 *global.Configuration             `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	StorageGrpcClient      *grpc.ClientConfiguration         `protobuf:"bytes,2,opt,name=storage_grpc_client,json=storageGrpcClient,proto3" json:"storage_grpc_client,omitempty"`
	SchedulerGrpcClient    *grpc.ClientConfiguration         `protobuf:"bytes,3,opt,name=scheduler_grpc_client,json=schedulerGrpcClient,proto3" json:"scheduler_grpc_client,omitempty"`
	BuildDirectories       []*BuildDirectoryConfiguration    `protobuf:"bytes,4,rep,name=build_directories,json=buildDirectories,proto3" json:"build_directories,omitempty"`
	FilePool               *filesystem.FilePoolConfiguration `protobuf:"bytes,5,opt,name=file_pool,json=filePool,proto3" json:"file_pool,omitempty"`
	LocalObjectStore       *local.StoreConfiguration         `protobuf:"bytes,7,opt,name=local_object_store,json=localObjectStore,proto3" json:"local_object_store,omitempty"`
	ParsedObjectPool       *parser.ParsedObjectPool          `protobuf:"bytes,6,opt,name=parsed_object_pool,json=parsedObjectPool,proto3" json:"parsed_object_pool,omitempty"`
	ObjectStoreConcurrency int64                             `protobuf:"varint,8,opt,name=object_store_concurrency,json=objectStoreConcurrency,proto3" json:"object_store_concurrency,omitempty"`
	ReapiRunners           []*ReapiRunnerConfiguration       `protobuf:"bytes,9,rep,name=reapi_runners,json=reapiRunners,proto3" json:"reapi_runners,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetStorageGrpcClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.StorageGrpcClient
	}
	return nil
}

func (x *ApplicationConfiguration) GetSchedulerGrpcClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.SchedulerGrpcClient
	}
	return nil
}

func (x *ApplicationConfiguration) GetBuildDirectories() []*BuildDirectoryConfiguration {
	if x != nil {
		return x.BuildDirectories
	}
	return nil
}

func (x *ApplicationConfiguration) GetFilePool() *filesystem.FilePoolConfiguration {
	if x != nil {
		return x.FilePool
	}
	return nil
}

func (x *ApplicationConfiguration) GetLocalObjectStore() *local.StoreConfiguration {
	if x != nil {
		return x.LocalObjectStore
	}
	return nil
}

func (x *ApplicationConfiguration) GetParsedObjectPool() *parser.ParsedObjectPool {
	if x != nil {
		return x.ParsedObjectPool
	}
	return nil
}

func (x *ApplicationConfiguration) GetObjectStoreConcurrency() int64 {
	if x != nil {
		return x.ObjectStoreConcurrency
	}
	return 0
}

func (x *ApplicationConfiguration) GetReapiRunners() []*ReapiRunnerConfiguration {
	if x != nil {
		return x.ReapiRunners
	}
	return nil
}

type BuildDirectoryConfiguration struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Runners       []*RunnerConfiguration      `protobuf:"bytes,1,rep,name=runners,proto3" json:"runners,omitempty"`
	Mount         *virtual.MountConfiguration `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildDirectoryConfiguration) Reset() {
	*x = BuildDirectoryConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDirectoryConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDirectoryConfiguration) ProtoMessage() {}

func (x *BuildDirectoryConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDirectoryConfiguration.ProtoReflect.Descriptor instead.
func (*BuildDirectoryConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP(), []int{1}
}

func (x *BuildDirectoryConfiguration) GetRunners() []*RunnerConfiguration {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *BuildDirectoryConfiguration) GetMount() *virtual.MountConfiguration {
	if x != nil {
		return x.Mount
	}
	return nil
}

type RunnerConfiguration struct {
	state                               protoimpl.MessageState                       `protogen:"open.v1"`
	Endpoint                            *grpc.ClientConfiguration                    `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Concurrency                         uint64                                       `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	PlatformPrivateKeys                 []string                                     `protobuf:"bytes,3,rep,name=platform_private_keys,json=platformPrivateKeys,proto3" json:"platform_private_keys,omitempty"`
	ClientCertificateVerifier           *x509.ClientCertificateVerifierConfiguration `protobuf:"bytes,4,opt,name=client_certificate_verifier,json=clientCertificateVerifier,proto3" json:"client_certificate_verifier,omitempty"`
	SizeClass                           uint32                                       `protobuf:"varint,5,opt,name=size_class,json=sizeClass,proto3" json:"size_class,omitempty"`
	IsLargestSizeClass                  bool                                         `protobuf:"varint,6,opt,name=is_largest_size_class,json=isLargestSizeClass,proto3" json:"is_largest_size_class,omitempty"`
	ShuffleDirectoryListings            bool                                         `protobuf:"varint,7,opt,name=shuffle_directory_listings,json=shuffleDirectoryListings,proto3" json:"shuffle_directory_listings,omitempty"`
	HiddenFilesPattern                  string                                       `protobuf:"bytes,8,opt,name=hidden_files_pattern,json=hiddenFilesPattern,proto3" json:"hidden_files_pattern,omitempty"`
	MaximumExecutionTimeoutCompensation *durationpb.Duration                         `protobuf:"bytes,9,opt,name=maximum_execution_timeout_compensation,json=maximumExecutionTimeoutCompensation,proto3" json:"maximum_execution_timeout_compensation,omitempty"`
	MaximumWritableFileUploadDelay      *durationpb.Duration                         `protobuf:"bytes,10,opt,name=maximum_writable_file_upload_delay,json=maximumWritableFileUploadDelay,proto3" json:"maximum_writable_file_upload_delay,omitempty"`
	MaximumFilePoolFileCount            uint64                                       `protobuf:"varint,11,opt,name=maximum_file_pool_file_count,json=maximumFilePoolFileCount,proto3" json:"maximum_file_pool_file_count,omitempty"`
	MaximumFilePoolSizeBytes            uint64                                       `protobuf:"varint,12,opt,name=maximum_file_pool_size_bytes,json=maximumFilePoolSizeBytes,proto3" json:"maximum_file_pool_size_bytes,omitempty"`
	WorkerId                            map[string]string                            `protobuf:"bytes,13,rep,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvironmentVariables                map[string]string                            `protobuf:"bytes,14,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BuildDirectoryOwnerUserId           uint32                                       `protobuf:"varint,15,opt,name=build_directory_owner_user_id,json=buildDirectoryOwnerUserId,proto3" json:"build_directory_owner_user_id,omitempty"`
	BuildDirectoryOwnerGroupId          uint32                                       `protobuf:"varint,16,opt,name=build_directory_owner_group_id,json=buildDirectoryOwnerGroupId,proto3" json:"build_directory_owner_group_id,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *RunnerConfiguration) Reset() {
	*x = RunnerConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerConfiguration) ProtoMessage() {}

func (x *RunnerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerConfiguration.ProtoReflect.Descriptor instead.
func (*RunnerConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RunnerConfiguration) GetEndpoint() *grpc.ClientConfiguration {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *RunnerConfiguration) GetConcurrency() uint64 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *RunnerConfiguration) GetPlatformPrivateKeys() []string {
	if x != nil {
		return x.PlatformPrivateKeys
	}
	return nil
}

func (x *RunnerConfiguration) GetClientCertificateVerifier() *x509.ClientCertificateVerifierConfiguration {
	if x != nil {
		return x.ClientCertificateVerifier
	}
	return nil
}

func (x *RunnerConfiguration) GetSizeClass() uint32 {
	if x != nil {
		return x.SizeClass
	}
	return 0
}

func (x *RunnerConfiguration) GetIsLargestSizeClass() bool {
	if x != nil {
		return x.IsLargestSizeClass
	}
	return false
}

func (x *RunnerConfiguration) GetShuffleDirectoryListings() bool {
	if x != nil {
		return x.ShuffleDirectoryListings
	}
	return false
}

func (x *RunnerConfiguration) GetHiddenFilesPattern() string {
	if x != nil {
		return x.HiddenFilesPattern
	}
	return ""
}

func (x *RunnerConfiguration) GetMaximumExecutionTimeoutCompensation() *durationpb.Duration {
	if x != nil {
		return x.MaximumExecutionTimeoutCompensation
	}
	return nil
}

func (x *RunnerConfiguration) GetMaximumWritableFileUploadDelay() *durationpb.Duration {
	if x != nil {
		return x.MaximumWritableFileUploadDelay
	}
	return nil
}

func (x *RunnerConfiguration) GetMaximumFilePoolFileCount() uint64 {
	if x != nil {
		return x.MaximumFilePoolFileCount
	}
	return 0
}

func (x *RunnerConfiguration) GetMaximumFilePoolSizeBytes() uint64 {
	if x != nil {
		return x.MaximumFilePoolSizeBytes
	}
	return 0
}

func (x *RunnerConfiguration) GetWorkerId() map[string]string {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

func (x *RunnerConfiguration) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *RunnerConfiguration) GetBuildDirectoryOwnerUserId() uint32 {
	if x != nil {
		return x.BuildDirectoryOwnerUserId
	}
	return 0
}

func (x *RunnerConfiguration) GetBuildDirectoryOwnerGroupId() uint32 {
	if x != nil {
		return x.BuildDirectoryOwnerGroupId
	}
	return 0
}

type ReapiRunnerConfiguration struct {
	state                     protoimpl.MessageState                       `protogen:"open.v1"`
	ReapiGrpcClient           *grpc.ClientConfiguration                    `protobuf:"bytes,1,opt,name=reapi_grpc_client,json=reapiGrpcClient,proto3" json:"reapi_grpc_client,omitempty"`
	InstanceName              string                                       `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Queue                     ReapiRunnerConfiguration_Queue               `protobuf:"varint,3,opt,name=queue,proto3,enum=bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration_Queue" json:"queue,omitempty"`
	Concurrency               uint64                                       `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	PlatformPrivateKeys       []string                                     `protobuf:"bytes,5,rep,name=platform_private_keys,json=platformPrivateKeys,proto3" json:"platform_private_keys,omitempty"`
	ClientCertificateVerifier *x509.ClientCertificateVerifierConfiguration `protobuf:"bytes,6,opt,name=client_certificate_verifier,json=clientCertificateVerifier,proto3" json:"client_certificate_verifier,omitempty"`
	SizeClass                 uint32                                       `protobuf:"varint,7,opt,name=size_class,json=sizeClass,proto3" json:"size_class,omitempty"`
	IsLargestSizeClass        bool                                         `protobuf:"varint,8,opt,name=is_largest_size_class,json=isLargestSizeClass,proto3" json:"is_largest_size_class,omitempty"`
	WorkerId                  map[string]string                            `protobuf:"bytes,9,rep,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ReapiRunnerConfiguration) Reset() {
	*x = ReapiRunnerConfiguration{}
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReapiRunnerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReapiRunnerConfiguration) ProtoMessage() {}

func (x *ReapiRunnerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReapiRunnerConfiguration.ProtoReflect.Descriptor instead.
func (*ReapiRunnerConfiguration) Descriptor() ([]byte, []int) {
	return file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ReapiRunnerConfiguration) GetReapiGrpcClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.ReapiGrpcClient
	}
	return nil
}

func (x *ReapiRunnerConfiguration) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *ReapiRunnerConfiguration) GetQueue() ReapiRunnerConfiguration_Queue {
	if x != nil {
		return x.Queue
	}
	return ReapiRunnerConfiguration_QUEUE_UNSPECIFIED
}

func (x *ReapiRunnerConfiguration) GetConcurrency() uint64 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *ReapiRunnerConfiguration) GetPlatformPrivateKeys() []string {
	if x != nil {
		return x.PlatformPrivateKeys
	}
	return nil
}

func (x *ReapiRunnerConfiguration) GetClientCertificateVerifier() *x509.ClientCertificateVerifierConfiguration {
	if x != nil {
		return x.ClientCertificateVerifier
	}
	return nil
}

func (x *ReapiRunnerConfiguration) GetSizeClass() uint32 {
	if x != nil {
		return x.SizeClass
	}
	return 0
}

func (x *ReapiRunnerConfiguration) GetIsLargestSizeClass() bool {
	if x != nil {
		return x.IsLargestSizeClass
	}
	return false
}

func (x *ReapiRunnerConfiguration) GetWorkerId() map[string]string {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

var File_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto protoreflect.FileDescriptor

const file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc = "" +
	"\n" +
	"Ibonanza.build/pkg/proto/configuration/bonanza_worker/bonanza_worker.proto\x12$bonanza.configuration.bonanza_worker\x1a?bonanza.build/pkg/proto/configuration/model/parser/parser.proto\x1aFbonanza.build/pkg/proto/configuration/storage/object/local/local.proto\x1a\\github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem/filesystem.proto\x1aagithub.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem/virtual/virtual.proto\x1aKgithub.com/buildbarn/bb-storage/pkg/proto/configuration/global/global.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/grpc/grpc.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/x509/x509.proto\x1a\x1egoogle/protobuf/duration.proto\"\xe4\x06\n" +
	"\x18ApplicationConfiguration\x12E\n" +
	"\x06global\x18\x01 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12a\n" +
	"\x13storage_grpc_client\x18\x02 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x11storageGrpcClient\x12e\n" +
	"\x15scheduler_grpc_client\x18\x03 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x13schedulerGrpcClient\x12n\n" +
	"\x11build_directories\x18\x04 \x03(\v2A.bonanza.configuration.bonanza_worker.BuildDirectoryConfigurationR\x10buildDirectories\x12V\n" +
	"\tfile_pool\x18\x05 \x01(\v29.buildbarn.configuration.filesystem.FilePoolConfigurationR\bfilePool\x12l\n" +
	"\x12local_object_store\x18\a \x01(\v2>.bonanza.configuration.storage.object.local.StoreConfigurationR\x10localObjectStore\x12b\n" +
	"\x12parsed_object_pool\x18\x06 \x01(\v24.bonanza.configuration.model.parser.ParsedObjectPoolR\x10parsedObjectPool\x128\n" +
	"\x18object_store_concurrency\x18\b \x01(\x03R\x16objectStoreConcurrency\x12c\n" +
	"\rreapi_runners\x18\t \x03(\v2>.bonanza.configuration.bonanza_worker.ReapiRunnerConfigurationR\freapiRunners\"\xc8\x01\n" +
	"\x1bBuildDirectoryConfiguration\x12S\n" +
	"\arunners\x18\x01 \x03(\v29.bonanza.configuration.bonanza_worker.RunnerConfigurationR\arunners\x12T\n" +
	"\x05mount\x18\x02 \x01(\v2>.buildbarn.configuration.filesystem.virtual.MountConfigurationR\x05mount\"\xd7\n" +
	"\n" +
	"\x13RunnerConfiguration\x12M\n" +
	"\bendpoint\x18\x01 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\bendpoint\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x04R\vconcurrency\x122\n" +
	"\x15platform_private_keys\x18\x03 \x03(\tR\x13platformPrivateKeys\x12\x84\x01\n" +
	"\x1bclient_certificate_verifier\x18\x04 \x01(\v2D.buildbarn.configuration.x509.ClientCertificateVerifierConfigurationR\x19clientCertificateVerifier\x12\x1d\n" +
	"\n" +
	"size_class\x18\x05 \x01(\rR\tsizeClass\x121\n" +
	"\x15is_largest_size_class\x18\x06 \x01(\bR\x12isLargestSizeClass\x12<\n" +
	"\x1ashuffle_directory_listings\x18\a \x01(\bR\x18shuffleDirectoryListings\x120\n" +
	"\x14hidden_files_pattern\x18\b \x01(\tR\x12hiddenFilesPattern\x12n\n" +
	"&maximum_execution_timeout_compensation\x18\t \x01(\v2\x19.google.protobuf.DurationR#maximumExecutionTimeoutCompensation\x12e\n" +
	"\"maximum_writable_file_upload_delay\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x1emaximumWritableFileUploadDelay\x12>\n" +
	"\x1cmaximum_file_pool_file_count\x18\v \x01(\x04R\x18maximumFilePoolFileCount\x12>\n" +
	"\x1cmaximum_file_pool_size_bytes\x18\f \x01(\x04R\x18maximumFilePoolSizeBytes\x12d\n" +
	"\tworker_id\x18\r \x03(\v2G.bonanza.configuration.bonanza_worker.RunnerConfiguration.WorkerIdEntryR\bworkerId\x12\x88\x01\n" +
	"\x15environment_variables\x18\x0e \x03(\v2S.bonanza.configuration.bonanza_worker.RunnerConfiguration.EnvironmentVariablesEntryR\x14environmentVariables\x12@\n" +
	"\x1dbuild_directory_owner_user_id\x18\x0f \x01(\rR\x19buildDirectoryOwnerUserId\x12B\n" +
	"\x1ebuild_directory_owner_group_id\x18\x10 \x01(\rR\x1abuildDirectoryOwnerGroupId\x1a;\n" +
	"\rWorkerIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x06\n" +
	"\x18ReapiRunnerConfiguration\x12]\n" +
	"\x11reapi_grpc_client\x18\x01 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x0freapiGrpcClient\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12Z\n" +
	"\x05queue\x18\x03 \x01(\x0e2D.bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.QueueR\x05queue\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x04R\vconcurrency\x122\n" +
	"\x15platform_private_keys\x18\x05 \x03(\tR\x13platformPrivateKeys\x12\x84\x01\n" +
	"\x1bclient_certificate_verifier\x18\x06 \x01(\v2D.buildbarn.configuration.x509.ClientCertificateVerifierConfigurationR\x19clientCertificateVerifier\x12\x1d\n" +
	"\n" +
	"size_class\x18\a \x01(\rR\tsizeClass\x121\n" +
	"\x15is_largest_size_class\x18\b \x01(\bR\x12isLargestSizeClass\x12i\n" +
	"\tworker_id\x18\t \x03(\v2L.bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.WorkerIdEntryR\bworkerId\x1a;\n" +
	"\rWorkerIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x05Queue\x12\x15\n" +
	"\x11QUEUE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vQUEUE_SMALL\x10\x01\x12\x0e\n" +
	"\n" +
	"QUEUE_LINK\x10\x02B6Z4bonanza.build/pkg/proto/configuration/bonanza_workerb\x06proto3"

var (
	file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescOnce sync.Once
	file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescData []byte
)

func file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescGZIP() []byte {
	file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescOnce.Do(func() {
		file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc), len(file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc)))
	})
	return file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDescData
}

var file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_goTypes = []any{
	(ReapiRunnerConfiguration_Queue)(0),      // 0: bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.Queue
	(*ApplicationConfiguration)(nil),         // 1: bonanza.configuration.bonanza_worker.ApplicationConfiguration
	(*BuildDirectoryConfiguration)(nil),      // 2: bonanza.configuration.bonanza_worker.BuildDirectoryConfiguration
	(*RunnerConfiguration)(nil),              // 3: bonanza.configuration.bonanza_worker.RunnerConfiguration
	(*ReapiRunnerConfiguration)(nil),         // 4: bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration
	nil,                                      // 5: bonanza.configuration.bonanza_worker.RunnerConfiguration.WorkerIdEntry
	nil,                                      // 6: bonanza.configuration.bonanza_worker.RunnerConfiguration.EnvironmentVariablesEntry
	nil,                                      // 7: bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.WorkerIdEntry
	(*global.Configuration)(nil),             // 8: buildbarn.configuration.global.Configuration
	(*grpc.ClientConfiguration)(nil),         // 9: buildbarn.configuration.grpc.ClientConfiguration
	(*filesystem.FilePoolConfiguration)(nil), // 10: buildbarn.configuration.filesystem.FilePoolConfiguration
	(*local.StoreConfiguration)(nil),         // 11: bonanza.configuration.storage.object.local.StoreConfiguration
	(*parser.ParsedObjectPool)(nil),          // 12: bonanza.configuration.model.parser.ParsedObjectPool
	(*virtual.MountConfiguration)(nil),       // 13: buildbarn.configuration.filesystem.virtual.MountConfiguration
	(*x509.ClientCertificateVerifierConfiguration)(nil), // 14: buildbarn.configuration.x509.ClientCertificateVerifierConfiguration
	(*durationpb.Duration)(nil),                         // 15: google.protobuf.Duration
}
var file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_depIdxs = []int32{
	8,  // 0: bonanza.configuration.bonanza_worker.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	9,  // 1: bonanza.configuration.bonanza_worker.ApplicationConfiguration.storage_grpc_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	9,  // 2: bonanza.configuration.bonanza_worker.ApplicationConfiguration.scheduler_grpc_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	2,  // 3: bonanza.configuration.bonanza_worker.ApplicationConfiguration.build_directories:type_name -> bonanza.configuration.bonanza_worker.BuildDirectoryConfiguration
	10, // 4: bonanza.configuration.bonanza_worker.ApplicationConfiguration.file_pool:type_name -> buildbarn.configuration.filesystem.FilePoolConfiguration
	11, // 5: bonanza.configuration.bonanza_worker.ApplicationConfiguration.local_object_store:type_name -> bonanza.configuration.storage.object.local.StoreConfiguration
	12, // 6: bonanza.configuration.bonanza_worker.ApplicationConfiguration.parsed_object_pool:type_name -> bonanza.configuration.model.parser.ParsedObjectPool
	4,  // 7: bonanza.configuration.bonanza_worker.ApplicationConfiguration.reapi_runners:type_name -> bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration
	3,  // 8: bonanza.configuration.bonanza_worker.BuildDirectoryConfiguration.runners:type_name -> bonanza.configuration.bonanza_worker.RunnerConfiguration
	13, // 9: bonanza.configuration.bonanza_worker.BuildDirectoryConfiguration.mount:type_name -> buildbarn.configuration.filesystem.virtual.MountConfiguration
	9,  // 10: bonanza.configuration.bonanza_worker.RunnerConfiguration.endpoint:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	14, // 11: bonanza.configuration.bonanza_worker.RunnerConfiguration.client_certificate_verifier:type_name -> buildbarn.configuration.x509.ClientCertificateVerifierConfiguration
	15, // 12: bonanza.configuration.bonanza_worker.RunnerConfiguration.maximum_execution_timeout_compensation:type_name -> google.protobuf.Duration
	15, // 13: bonanza.configuration.bonanza_worker.RunnerConfiguration.maximum_writable_file_upload_delay:type_name -> google.protobuf.Duration
	5,  // 14: bonanza.configuration.bonanza_worker.RunnerConfiguration.worker_id:type_name -> bonanza.configuration.bonanza_worker.RunnerConfiguration.WorkerIdEntry
	6,  // 15: bonanza.configuration.bonanza_worker.RunnerConfiguration.environment_variables:type_name -> bonanza.configuration.bonanza_worker.RunnerConfiguration.EnvironmentVariablesEntry
	9,  // 16: bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.reapi_grpc_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	0,  // 17: bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.queue:type_name -> bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.Queue
	14, // 18: bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.client_certificate_verifier:type_name -> buildbarn.configuration.x509.ClientCertificateVerifierConfiguration
	7,  // 19: bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.worker_id:type_name -> bonanza.configuration.bonanza_worker.ReapiRunnerConfiguration.WorkerIdEntry
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_init() }
func file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_init() {
	if File_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc), len(file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_goTypes,
		DependencyIndexes: file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_depIdxs,
		EnumInfos:         file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_enumTypes,
		MessageInfos:      file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_msgTypes,
	}.Build()
	File_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto = out.File
	file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_goTypes = nil
	file_bonanza_build_pkg_proto_configuration_bonanza_worker_bonanza_worker_proto_depIdxs = nil
}
